---
title: "IL12B"
author: "Tea Heikkilä, Emilia Kaiser & Jaakko Koskenniemi"
output: html_document
date: '2022-24-04'
editor_options:
  chunk_output_type: console
---

Load packages and import data
```{r}
library(tidyverse)
library(data.table)
library(coloc)
library(TwoSampleMR)
library(ggpubr)
library(ieugwasr)
library(rio)
library(here)

here::i_am("analyses/IL12B.Rmd")


IL12B_prot <- read_exposure_data("data/export/IL12B_prot_anno_TwoSampleMR.csv", sep=",")
IL12B_T1D  <- read_outcome_data("data/export/IL12B_T1D_TwoSampleMR.csv", sep=",")

IL12B <- harmonise_data(IL12B_prot, IL12B_T1D)

```

## Manhattan plots

No GWAS hits were seen for the risk of T1D so no coloc/MR is done.

```{r}
#create Manhattan plots with vertical lines indicating the selected area (see below 2.4)
IL12B_prot.fig <-
  IL12B %>%
  ggplot(aes(x = pos.exposure/1000, y=-log10(pval.exposure))) +
  geom_point()+
  geom_hline(yintercept=8, linetype="dashed")+
  # geom_vline(xintercept=36.9e6/1000, linetype="dashed")+
  # geom_vline(xintercept=37.3e6/1000, linetype="dashed")+
  ggtitle("GWAS of IL12B in serum") +
  ylab("-log10(p)") +
  xlab(NULL)

IL12B_T1D.fig <-
  IL12B %>%
  ggplot()+
  geom_point(mapping=aes(x = pos.exposure/1000, y=-log10(pval.outcome))) +
  geom_hline(yintercept=8, linetype="dashed")+
  # geom_vline(xintercept=36.9e6/1000, linetype="dashed")+
  # geom_vline(xintercept=37.3e6/1000, linetype="dashed")+
  ggtitle("GWAS of risk of T1D") +
  ylab("-log10(p)") +
  xlab("position(kbp)")

#Obtain range for figure of gene
layer_scales(IL12B_T1D.fig)$x$range$range

IL12B_gene.fig <-
  ggplot(data = IL12B) +
  geom_blank() +
  geom_segment(x=37521.878, xend=37571.094, y=1, yend=1, linewidth = 2) +
  annotate("text", label = "IL12B",
           x= (37521.878 + 37571.094) / 2, y=1, hjust = 0.5, vjust = -1) +
  xlim(36521.878, 38571.094) +
  ylim(0.75, 2) +
  ylab(NULL) + xlab(NULL) +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank())

fig_IL12B_manhattan <- ggarrange(IL12B_gene.fig, IL12B_prot.fig, IL12B_T1D.fig,
                                 heights = c(1, 3, 3), nrow = 3,
                                 ncol = 1, align = "hv")
fig_IL12B_manhattan
# ggsave("figures/IL12B-manhattan-combined-fig.pdf",
#        height = 6, width = 8, units = "in")
```


