---
title: "IL2RB"
author: "Tea Heikkilä, Emilia Kaiser & Jaakko Koskenniemi"
output:
  html_document:
    toc: yes
    toc_float: yes
    number_sections: yes
    code_folding: hide
date: '2023-12-01'
editor_options: 
  chunk_output_type: console
---

Load packages and import data
```{r}
pacman::p_load(tidyverse, data.table, coloc,TwoSampleMR, ggpubr, 
               ieugwasr, rio, here)

here::i_am("analyses/IL2RB.Rmd")

source("code/01-Functions.R")
```


# eQTL

```{r}

IL2RB_eqtl <- import_data("data/export_harmonization/IL2RB_eqtl_TwoSampleMR.csv",
            "data/export_harmonization/IL2RB_T1D_TwoSampleMR.csv", has_beta = TRUE)

```

## Initial Manhattan plots
```{r}
manhattan_plots(IL2RB_eqtl, gene_start=37118666, gene_end=37175118, title = "IL2RB")
IL2RB_eqtl <- IL2RB_eqtl %>% filter(pos.outcome > 37068000 & pos.outcome < 37350000) 
manhattan_plots(IL2RB_eqtl, gene_start=37118666, gene_end=37175118, title = "IL2RB")

#ggsave("figures/IL2RB-eQTL-T1D-manhattan.png", height = 6, width = 6)

```

## Coloc assuming 1 causal variant
```{r}
coloc_results_IL2RB_eqtl <- analyze_coloc_eqtl(IL2RB_eqtl)
# coloc_results_IL2RB_eqtl$coloc_D1D2 #coloc results
# coloc_results_IL2RB_eqtl$D1 #data eQTL
# coloc_results_IL2RB_eqtl$D2 #data t1d

```

## Regional manhattan plot

```{r}

load("data/export_LDmat/IL2RB_LDmat.RDA")

plot_coloc(genechr = 22,
           fig_start = 37068000,
           fig_end = 37350000,
           coloc_results = coloc_results_IL2RB_eqtl$coloc_D1D2,
           data = IL2RB_eqtl,
           D1 = coloc_results_IL2RB_eqtl$D1,
           D2 = coloc_results_IL2RB_eqtl$D2,
           LDmat = IL2RB)

ggsave(filename = "figures/IL2RB.png", height = 8, width = 6)
```



## Functional variants

```{r}
load("data/export_functional_variants/phenoscanner-entries.RDS")


#Find IL2RB missense variants
IL2RB_missense <- functional_variants$IL2RB$results %>% 
  filter(consequence == "missense") %>%  
  distinct(rsid) %>% pull()

IL2RB_missense #rs143857582, rs149508414

#give betas and se for eQTL and T1D risk (note, this is not MR!)
IL2RB_eqtl %>%
  filter(SNP %in% IL2RB_missense) %>%
  select(SNP, beta.outcome, se.outcome, pval.outcome, beta.exposure, pval.exposure) %>%
  mutate(across(!matches(c("SNP", "pval.outcome", "pval.exposure")), function(x) signif(x, digits = 2))) #none

```





