---
title: "IL2RA"
author: "Tea Heikkilä, Emilia Kaiser & Jaakko Koskenniemi"
output:
  html_document:
    toc: yes
    toc_float: yes
    number_sections: yes
    code_folding: hide
date: '2022-05-03'
editor_options:
  chunk_output_type: console
---

Load packages and import data
```{r}
pacman::p_load(tidyverse, data.table, coloc, TwoSampleMR, ggpubr, 
               ieugwasr, rio, here)

here::i_am("analyses/IL2RA.Rmd")

source("code/Functions.R")
```


# eQTL

TwoSampleMR is used to harmonize the data even though TwoSampleMR is not run. Therefore, data includes variable "beta" which is actually a z-score

```{r}
IL2RA_eqtl <- import_data("data/export/IL2RA_eqtl_TwoSampleMR.csv",
            "data/export/IL2RA_T1D_TwoSampleMR.csv", has_beta = TRUE)

```

## Initial Manhattan plots
```{r}
manhattan_plots(IL2RA_eqtl, gene_start=6010689, gene_end=6062370, title = "IL2RA")
IL2RA_eqtl <- IL2RA_eqtl %>% filter(pos.outcome > 5780000 & pos.outcome < 6250000) 
manhattan_plots(IL2RA_eqtl, gene_start=6010689, gene_end=6062370, title = "IL2RA")
```

## Coloc assuming 1 causal variant
```{r}
coloc_results_IL2RA_eqtl <- analyze_coloc_eqtl(IL2RA_eqtl)
# coloc_results_IL2RA_eqtl$coloc_D1D2 #coloc results
# coloc_results_IL2RA_eqtl$D1 #data eQTL
# coloc_results_IL2RA_eqtl$D2 #data t1d

```

## Regional manhattan plot

```{r}

load("data/export/IL2RA_LDmat.RData")

plot_coloc(genechr = 10,
           fig_start = 5780000,
           fig_end = 6250000,
           coloc_results = coloc_results_IL2RA_eqtl$coloc_D1D2,
           data = IL2RA_eqtl,
           D1 = coloc_results_IL2RA_eqtl$D1,
           D2 = coloc_results_IL2RA_eqtl$D2,
           LDmat = IL2RA)

ggsave(filename = "figures/IL2RA.png", height = 8, width = 6)
```

## MR
```{r}

IL2RA_eqtl_rs61839660   <- IL2RA_eqtl %>% filter(SNP == "rs61839660")
MR_IL2RA_eqtl_rs61839660   <- TwoSampleMR::mr(IL2RA_eqtl_rs61839660)

MR_IL2RA_eqtl_rs61839660

exp(MR_IL2RA_eqtl_rs61839660$b)
exp(MR_IL2RA_eqtl_rs61839660$b - 1.96*MR_IL2RA_eqtl_rs61839660$se)
exp(MR_IL2RA_eqtl_rs61839660$b + 1.96*MR_IL2RA_eqtl_rs61839660$se)
```


## Functional variants

```{r}
load("data/export/phenoscanner-functional-variants-rsids.RDS")

IL2RA_eqtl_orig <- read_csv("data/export/IL2RA_eqtl_TwoSampleMR.csv")
IL2RA_eqtl_orig %>%
  filter(SNP == "rs72650666") #no

IL2RA_T1D <- read_csv("data/export/IL2RA_T1D_TwoSampleMR.csv")
IL2RA_T1D %>%
  filter(SNP == "rs72650666") #no

```


## Find top hit
```{r}
#IL2RA_eqtl <- IL2RA_eqtl %>%
#    mutate(eaf.exposure = as.numeric(eaf.exposure)) %>%
#    mutate(eaf.outcome  = as.numeric(eaf.outcome)) %>%
#    mutate(maf.exposure  =
#             ifelse(eaf.exposure  < 0.5, eaf.exposure,
#                    1 - eaf.exposure)) %>%
#    mutate(maf.outcome  =
#             ifelse(eaf.outcome  < 0.5, eaf.outcome,
#                    1 - eaf.outcome))

#  IL2RA_eqtl <- IL2RA_eqtl %>%
#    filter(!is.na(pos.outcome))


#  anyNA(IL2RA_eqtl$maf.exposure) & #anyNA(IL2RA_eqtl$maf.outcome)
#  anyNA(IL2RA_eqtl$pos.outcome)
  
  
#D1 <- list(
#      type = "quant", # quantitative trait
#      pvalues = IL2RA_eqtl$pval.exposure,
#      N = IL2RA_eqtl$samplesize.exposure,
#      MAF = IL2RA_eqtl$maf.exposure,
#      pos = IL2RA_eqtl$pos.outcome,
#      snp = IL2RA_eqtl$SNP,
#      sdY = 1)

#D2 <- list(
#      type = "cc", # case-control trait
#      pvalues = IL2RA_eqtl$pval.outcome,
#      N = 18942+501638, # Case-control study (Chiou et al. #2021 Nature)
#      s = 18942/(18942+501638), # N_case/(N_case+ N_ctrl)
#      MAF = IL2RA_eqtl$maf.exposure,  #eqtl used here in #purpose
#      pos = IL2RA_eqtl$pos.outcome,
#      snp = IL2RA_eqtl$SNP)

#coloc_results <- coloc.abf(D1, D2, p1 = 1e-4, p2 = 1e-4, #p12 = 1e-5)

#Find top SNP
#coloc_results$results[which(coloc_results$results$SNP.PP.H4#==max(coloc_results$results$SNP.PP.H4)),"snp"]

#IL2RA_eqtl_top <- IL2RA_eqtl %>% 
#  filter(SNP == "rs61839660") %>% 
#  select(SNP, zscore.exposure, beta.outcome, se.outcome) 

#IL2RA_eqtl_top %>%
#  mutate(zscore.exposure = round(zscore.exposure),
#        beta.outcome = round(beta.outcome, 2),
#        exp_beta.T1D = round(exp(beta.outcome), 2),
#         exp_ci_95_low.T1D = round(exp(beta.outcome - #1.96*se.outcome), 2),
#         exp_ci_95_high.T1D = round(exp(beta.outcome + #1.96*se.outcome), 2)) %>% 
#  rename(zscore.IL2RA = zscore.exposure,
#         beta.T1D = beta.outcome) %>%
#  knitr::kable()
```




# pQTL
```{r}

#IL2RA_pqtl <- import_data("data/export/IL2RA_prot_anno_TwoS#ampleMR.csv",
#            "data/export/IL2RA_T1D_TwoSampleMR.csv", #has_beta = TRUE)

```


## Manhattan plots
```{r}

#manhattan_plots(IL2RA_pqtl, gene_start=6052652, #gene_end=6104288, title = "IL2RA")
#ggsave("figures/IL2RA-pQTL-T1D-manhattan.png", height = 6, #width = 6)
```

## Coloc assuming 1 causal variant
```{r}
#analyze_coloc_pqtl(IL2RA_pqtl)
```

