---
title: "IL6ST"
author: "Tea Heikkilä, Emilia Kaiser & Jaakko Koskenniemi"
output: html_document
date: '2023-12-01'
editor_options:
  chunk_output_type: console
---

  Load packages and import data
```{r}

source("code/01-Functions.R")
here::i_am("analyses/IL6ST.Rmd")
```


```{r}
IL6ST_pqtl <- import_data("data/export_harmonization/IL6ST_prot_anno_TwoSampleMR.csv",
                          "data/export_harmonization/IL6ST_T1D_TwoSampleMR.csv", 
                          has_beta=TRUE)
```

## Manhattan plots

```{r}
manhattan_plots(IL6ST_pqtl, gene_start = 55935095, gene_end = 55995022,
               title = "IL6ST")

IL6ST_pqtl <- IL6ST_pqtl %>% filter(pos.outcome > 55600000 & pos.outcome < 56200000) 
manhattan_plots(IL6ST_pqtl, gene_start = 55935095, gene_end = 55995022,
               title = "IL6ST")

```


## Coloc for pQTL

```{r}
coloc_IL6ST_pqtl <- analyze_coloc_pqtl(IL6ST_pqtl)


coloc_IL6ST_pqtl$coloc_D1D2

```

#Coloc for eQTL

```{r}
IL6ST_eqtl <- import_data("data/export_harmonization/IL6ST_eqtl_TwoSampleMR.csv",
            "data/export_harmonization/IL6ST_T1D_TwoSampleMR.csv", has_beta = TRUE)

analyze_coloc_eqtl(IL6ST_eqtl)$coloc_results
coloc_IL6ST_eqtl <- analyze_coloc_eqtl(IL6ST_eqtl)


str(coloc_IL6ST_eqtl)
coloc_IL6ST_eqtl$sensitivity
top_snp <- coloc_IL6ST_eqtl$coloc_D1D2$results[coloc_IL6ST_eqtl$coloc_D1D2$results$SNP.PP.H4 ==
                                         max(coloc_IL6ST_eqtl$coloc_D1D2$results$SNP.PP.H4), ]
top_snp <- top_snp$snp # "rs7731626"
```


#MR 
```{r}

IL6ST_eqtl_rs7731626 <- IL6ST_eqtl %>% 
  filter(SNP == top_snp)

IL6ST_eqtl_rs7731626 %>% 
  mutate(Fstat = (beta.exposure/se.exposure)^2) 

mr_IL6ST_rs7731626 <- IL6ST_eqtl_rs7731626 %>% 
  mr()

generate_odds_ratios(mr_IL6ST_rs7731626) %>% 
  select(or, or_lci95, or_uci95, pval) %>% 
  mutate(across(everything(), ~signif(.x, 3)))
```


# Regional manhattan plot for eQTL coloc
```{r}

load("data/export_LDmat/IL6ST_eqtl_LDmat.rda")

plot_coloc(genechr = 5,
           fig_start = 55600000,
           fig_end = 56200000,
           coloc_results = coloc_IL6ST_eqtl$coloc_D1D2,
           data = IL6ST_eqtl,
           D1 = coloc_IL6ST_eqtl$D1,
           D2 = coloc_IL6ST_eqtl$D2,
           LDmat = IL6ST)

ggsave(filename = "figures/IL6ST_eqtl.png", height = 8, width = 6)

load("data/export_LDmat/IL6ST_pqtl_LDmat.rda")
plot_coloc(genechr = 5,
           fig_start = 55600000,
           fig_end = 56200000,
           coloc_results = coloc_IL6ST_pqtl$coloc_D1D2,
           data = IL6ST_pqtl,
           D1 = coloc_IL6ST_pqtl$D1,
           D2 = coloc_IL6ST_pqtl$D2,
           LDmat = IL6ST)

ggsave(filename = "figures/IL6ST_pqtl.png", height = 8, width = 6)
```


## Functional variants

```{r}
load("data/export_functional_variants/phenoscanner-entries.RDS")

#Find IL6ST missense variants
IL6ST_missense <- functional_variants$IL6ST$results %>% 
  filter(consequence == "missense") %>%  
  distinct(rsid) %>% pull()

IL6ST_missense #rs61748224, rs61755738, rs34417936, rs141500365

#give betas and se for eQTL and T1D risk (note, this is not MR!)
IL6ST_pqtl %>%
  filter(SNP %in% IL6ST_missense) %>%
  mutate(Fstat = (beta.exposure/se.exposure)^2) %>% 
  select(SNP, beta.outcome, se.outcome, pval.outcome, beta.exposure, pval.exposure, Fstat) %>%
  mutate(across(!matches(c("SNP", "pval.outcome", "pval.exposure")), function(x) signif(x, digits = 2)))


#Select only rs141500365 (as p for its exposure is < 10^-5) and run MR
IL6ST_pqtl_funcvar_mr <- IL6ST_pqtl %>%caht
  filter(SNP %in% c("rs141500365")) %>%
  TwoSampleMR::mr_singlesnp() %>%
  mutate(exp_b = exp(b), 
         lo_95 = exp(b - (1.96 * se)),
         hi_95 = exp(b + (1.96 * se))) %>%
    mutate(across(starts_with(c("b", "se","p", "exp_b", "lo", "hi")), function(x) signif(x, digits = 2)))

  IL6ST_pqtl_funcvar_mr %>% 
    select(-id.exposure, -id.outcome, -samplesize) %>% 
    knitr::kable()

```




